# Site settings
title: Rotating Christmas Tree Stand
description: Make your live holiday tree even better by viewing at all angles.
baseurl: "/rotating-christmas-tree-stand"
url: "https://jonasbaldwin.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Permalinks
permalink: /:categories/:year/:month/:day/:title.html

